### ISSUE TITLE
Module 1 - Lesson 2 - java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by almir-campos** [eugenp/REST-With-Spring#101]
When I run the M1-L2 just after cloning it, I get this error message:

```
13:46:34.884 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [com/baeldung/um/spring/UmPersistenceJpaConfig.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
```

It only works when I add the following dependency to `um-webapp-m2-l1-start/pom.xml`:

```
<dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.1</version>
</dependency>
```
Is this a case of adding this dependency to the project?

@eugenp 
UPDATE: Module 3 - same problem, same solution.

**Comment by lor6** [comment]
Hi @almir-campos  This is an issue you'll see if you use a higher Java version than Java 8. 
The codebase is currently built using JDK 8, so you should use this version to run the projects. For Java 9 and above, you'll need to add that dependency, as the jaxb module is no longer included in JDK9+.
