### ISSUE TITLE
please help me to find url to run this project https://github.com/eugenp/REST-With-Spring

### ISSUE THREAD

**Issue by sesepehr** [eugenp/REST-With-Spring#64]
could u help me.

**Comment by eugenp** [comment]
Hi, 
First - sure, I can have a look - what exactly is the problem. 
Second - github issues are not a good way to talk generally like this - they're much more for specific, to the point technical issues. So - go ahead and email me (reply to any of my emails) and I'd be happy to help. Cheers, 
Eugen.

**Comment by sesepehr** [comment]
Hi ,
Sorry for type of problem,i dont know what did i do ehn run it on tomcat
,wich url run to work your project and connect to it
thank you sir,
Best Regards

**Comment by sesepehr** [comment]
---------- Forwarded message ----------
From: Sepehr Naderi <sep.naderi@gmail.com>
Date: Wed, Jan 6, 2016 at 11:35 PM
Subject: Re: [REST-With-Spring] please help me to find url to run this
project https://github.com/eugenp/REST-With-Spring (#64)
To: eugenp/REST-With-Spring <
reply@reply.github.com
>


Hi ,
Sorry for type of problem,i dont know what did i do ehn run it on tomcat
,wich url run to work your project and connect to it
thank you sir,
Best Regards

**Comment by sesepehr** [comment]
i need the url path after rub this this project to run

**Comment by sesepehr** [comment]
hi
i could not find method and url to connetc your projetc locally,please
guide me ..
thanks sir
