### ISSUE TITLE
error in mvn install on path guide 

### ISSUE THREAD

**Issue by sesepehr** [eugenp/REST-With-Spring#66]
[INFO] user-management-parent ............................ SUCCESS [0.338s]
[INFO] common ............................................ FAILURE [1.254s]
[INFO] common-client ..................................... SKIPPED
[INFO] common-test ....................................... SKIPPED
[INFO] um-client ......................................... SKIPPED
[INFO] um-webapp ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.272s
[INFO] Finished at: Sat Jan 09 12:20:22 IRST 2016
[INFO] Final Memory: 15M/162M

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project common: Fatal error compiling: invalid target release: 1.8 -> [Help 1]

[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by eugenp** [comment]
That is odd - there is a CI env set up to build every branch of the project and nothing is failing [over there](https://rest-security.ci.cloudbees.com/view/REST-With-Spring/). 
Also, I can't reproduce it locally either - can you have a look if you're using the latest version of the codebase (and what branch you're on). 
Thanks, 
Eugen.

**Comment by sesepehr** [comment]
Hi.sir
i could run you project on Centos with Jdk1.8 ,but i have this error when
rest run

curl --user admin@fake.com:adminpass -H "Content-Type: application/json" -i
--data '{ "name":"newRoleName" }'
http://localhost:8080/rest-sec/api/privileges


HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
Date: Mon, 11 Jan 2016 11:49:15 GMT
Connection: close

**Comment by eugenp** [comment]
First - what branch are you running on?

**Comment by sesepehr** [comment]
First i want  to run local version in my computer to test ,
could i import user& pass , rolename on curl
please help me the command on curl to send data or parameters
,

**Comment by giorgosart** [comment]
@sesepehr Make sure that your JAVA_HOME points to a Java 8 installation

**Fatal error compiling: invalid target release: 1.8**
