### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by jbenhamou** [eugenp/REST-With-Spring#70]
Which Java code formatter should be used:

1. [Java](https://github.com/eugenp/REST-With-Spring/wiki/Eclipse:-Setup-and-Configuration#java)
2. [set up Eclipse formatter](set up Eclipse formatter)

**Comment by eugenp** [comment]
Hey @jbenhamou - the documentation should now be clearer about the formatter. 
Hope that sorts things out, but if you have any issues - just re-open this one here. Cheers, 
Eugen.
