### ISSUE TITLE
Can't Login with provided credentials

### ISSUE THREAD

**Issue by apeixinho** [eugenp/REST-With-Spring#72]
After following the procedure, described in main project page.

No build errors, application starts correctly on STS using BootDashboard.

The credentials in the properties files

**username**=restUser
**password**=restmy5ql

Don't work.

Which credentials should I use then?

**Comment by almir-campos** [comment]
Ok, 2016, but... what's the error message?

**Comment by lor6** [comment]
The credentials 
username=restUser
password=restmy5ql

are for a the MySql user, if the project is configured to use MySql. For the modules that have security enabled, the credentials are:
admin@fake.com / adminpass
user@fake.com / userpass
