### ISSUE TITLE
WebConstants Interface

### ISSUE THREAD

**Issue by zhenyanghua** [eugenp/REST-With-Spring#79]
[WebConstants.java](https://github.com/eugenp/REST-With-Spring/blob/module1/m1-lesson3-start/common/src/main/java/com/baeldung/common/web/WebConstants.java) 
@eugenp I don't quite understand why an interface is used here to define the constants instead of using a final class with private constructor and static fields. Is there an advantage in this project to use an interface to define constants? (PS - I am still working my way to fully understand the codebase before moving on to the REST related lessons in the module 1).

**Comment by eugenp** [comment]
Hey @zhenyanghua - no reason, an explicit constant would be perfectly fine as well. Keep in mind that fields in an interface are implicitly public static final - so they're constants as well. 
Hope that clears things up. 
qce

**Comment by zhenyanghua** [comment]
Yes, that makes sense. Thanks!
