### ISSUE TITLE
findPaginatedInternal

### ISSUE THREAD

**Issue by zhenyanghua** [eugenp/REST-With-Spring#80]
@eugenp I am confused with the [findPaginatedInternal](https://github.com/eugenp/REST-With-Spring/blob/module1/m1-lesson3-start/common/src/main/java/com/baeldung/common/web/controller/AbstractReadOnlyController.java#L60-L67) definition. the service has a method called `findAllPaginated`, why the `findAllPaginationAndSortedRaw` is used instead inside of the `findPaginatedInternal`? 

so why don't we use the following instead?
```java
protected final List<T> findPaginatedInternal(final int page, final int size) {
        final List<T> resultPage = getService().findAllPaginated(page, size);
        return resultPage;
}
```

**Comment by eugenp** [comment]
Hey @zhenyanghua - the naming conventions there aren't 100% consistent, that's a good point - that method shouldn't accept sorting params. I'll make a note of it and fix it soon - thanks for the heads up. 
Cheers, 
Eugen.

**Comment by zhenyanghua** [comment]
@eugenp thanks for clearing things out.

In the following three controllers, the `findAllPaginated` is used, but the method under the hood is `findPaginatedAndSortedInternal(page, size, null, null);` I assume it will be updated to use `findPaginatedInternal(page, size)` instead?

[UserController](https://github.com/eugenp/REST-With-Spring/blob/module1/m1-lesson3-start/um-webapp/src/main/java/com/baeldung/um/web/controller/UserController.java#L48-L53)

[RoleController](https://github.com/eugenp/REST-With-Spring/blob/module1/m1-lesson3-start/um-webapp/src/main/java/com/baeldung/um/web/controller/RoleController.java#L48-L53)

[PrivilegeController](https://github.com/eugenp/REST-With-Spring/blob/module1/m1-lesson3-start/um-webapp/src/main/java/com/baeldung/um/web/controller/PrivilegeController.java#L48-L53)

**Comment by eugenp** [comment]
Yeah, exactly. 
But, as with any codebase level change - I have to be careful with how that matches up to the video, so it will be a bit of a slow process. The team will first have a look to see if these methods are discussed explicitly in any of the lesson videos. Then, I'll make the changes. 
So, it's in progress :)
Cheers, 
Eugen.

**Comment by zhenyanghua** [comment]
Thanks for the info!

Zhenyang Hua

**Comment by eugenp** [comment]
Quick update here - should be ready in about a week.

**Comment by lor6** [comment]
The issue is now fixed, closing this.
