### ISSUE TITLE
could not run UM-UI-M4-L1

### ISSUE THREAD

**Issue by sasinandan** [eugenp/REST-With-Spring#82]
HI,
I am quite new to Spring Java, when i try to run the UM-UI on port 8083, i do not see any thing on my screen(http://localhost:8083), i see two errors,

1) In my Pom.xml,

At the execution tag, i get as below,

Could not get the value for parameter contextFolder for plugin execution default (ro.isdc.wro4j:wro4j-maven-plugin:
 1.8.0:run:default:generate-resources) org.eclipse.core.runtime.CoreException: Could not get the value for parameter contextFolder 
 for plugin execution default at org.eclipse.m2e.core.internal.embedder.MavenImpl.getMojoParameterValue(MavenImpl.java:950) 
 at org.jboss.tools.m2e.wro4j.internal.Wro4jBuildParticipant.getContextRoots(Wro4jBuildParticipant.java:151) at 
 org.jboss.tools.m2e.wro4j.internal.Wro4jBuildParticipant.build(Wro4jBuildParticipant.java:86) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200) at org.eclipse.core.internal.events.BuildManager
 $2.run(BuildManager.java:735) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246) at org.eclipse.core.internal.events.BuildManager
 $1.run(BuildManager.java:301) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304) at 
 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360) at 
 org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383) at 
 org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144) at 
 org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:
 55) Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin ro.isdc.wro4j:wro4j-maven-plugin:1.8.0 or one of its 
 dependencies could not be resolved: Failure to transfer org.codehaus.plexus:plexus-utils:jar:2.0.6 from http://10.49.216.134:8080/
 nexus-2.0.6/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval 
 of nexus has elapsed or updates are forced. Original error: Could not transfer artifact org.codehaus.plexus:plexus-utils:jar:2.0.6 
 from/to nexus (http://10.49.216.134:8080/nexus-2.0.6/content/groups/public): Failed to transfer http://10.49.216.134:8080/
 nexus-2.0.6/content/groups/public/org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar. Error code 500, Internal Server 
 Error at 
 org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:
 218) at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:
 149) at 
 org.eclipse.m2e.core.internal.project.registry.EclipsePluginDependenciesResolver.resolve(EclipsePluginDependenciesResolver.java:
 59) at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:400) 
 at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:372) at 
 org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:231) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.getMojoParameterValue(MavenImpl.java:925) ... 26 more Caused by: 
 org.eclipse.aether.resolution.ArtifactResolutionException: Failure to transfer org.codehaus.plexus:plexus-utils:jar:2.0.6 from http://
 10.49.216.134:8080/nexus-2.0.6/content/groups/public was cached in the local repository, resolution will not be reattempted until 
 the update interval of nexus has elapsed or updates are forced. Original error: Could not transfer artifact 
 org.codehaus.plexus:plexus-utils:jar:2.0.6 from/to nexus (http://10.49.216.134:8080/nexus-2.0.6/content/groups/public): Failed to 
 transfer http://10.49.216.134:8080/nexus-2.0.6/content/groups/public/org/codehaus/plexus/plexus-utils/2.0.6/plexus-
 utils-2.0.6.jar. Error code 500, Internal Server Error at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) at 
 org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367) at 
 org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:
 210) ... 32 more Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Failure to transfer org.codehaus.plexus:plexus-
 utils:jar:2.0.6 from http://10.49.216.134:8080/nexus-2.0.6/content/groups/public was cached in the local repository, resolution will 
 not be reattempted until the update interval of nexus has elapsed or updates are forced. Original error: Could not transfer artifact 
 org.codehaus.plexus:plexus-utils:jar:2.0.6 from/to nexus (http://10.49.216.134:8080/nexus-2.0.6/content/groups/public): Failed to 
 transfer http://10.49.216.134:8080/nexus-2.0.6/content/groups/public/org/codehaus/plexus/plexus-utils/2.0.6/plexus-
 utils-2.0.6.jar. Error code 500, Internal Server Error at 
 org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:238) at 
 org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421) ... 35 more

2) during rung time, i see 
http://localhost:8083/js/angular-bootstrap.js
is returning 404 not found

can someone, please help me in solving this issue.

**Comment by eugenp** [comment]
Hey @sasinandan - looking into it. 
Cheers, 
Eugen.,

**Comment by sasinandan** [comment]
ok @eugenp ..thank you :)

**Comment by eugenp** [comment]
Hey @sasinandan - I ran the 2 projects and everything seems OK. 
Please make sure you clear your entire maven repo locally, run the full build on the parent and give it another go. 
Thanks, 
Eugen.

**Comment by sasinandan** [comment]
sure. @eugenp thank you..
