### ISSUE TITLE
IService declaration and IEntity - IDto relationships

### ISSUE THREAD

**Issue by gandesc** [eugenp/REST-With-Spring#90]
Hi,

I'm following the course and really enjoying it so far.

For the lesson repository [um-webapp-m2-l2](https://github.com/eugenp/REST-With-Spring/tree/module2), for the User Service, you've switched from directly using entities to using DTOs, which is great.

However, since the IService interface is declared as 

`public interface IService<T extends INameableEntity> ...`, 

you're forced to define UserDto as also extending NameableEntity:  

`public class UserDto implements INameableEntity, INameableDto`.

Is this intentional or is it something in need of a refactor? I think a DTO shouldn't have to implement an entity specific interface.

**Comment by lor6** [comment]
Update: a new lesson in Module 7 - "Decouple the controller from entities" was added to address the DTO-Entity conversion scenario.
